[package]
name = "libpg_query2-sys"
links = "pg_query"
description = "FFI bindings to libpg_query"
version = "0.3.0"
authors = ["Jasper Hugo <jasper@avstack.io>"]
build = "build.rs"
edition = "2018"
license = "BSD-3-Clause"
repository = "https://github.com/avstack/libpg_query2-sys"
